config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, except: [:new, :create]
  get "/sign_up", to: "registrations#new", as: "sign_up_form"
  post "/sign_up", to: "registrations#create", as: "sign_up"

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create_fb_session'
  get 'auth/failure', to: redirect('/')

  resources :listings, except: [:create]
  post "/listings/create", to: "listings#create", as: "create_listing"

  resources :listings_search, only: [:index, :create]

  resources :listings_photos, except: [:delete, :index]

  resources :bookings

  require 'sidekiq/web'
  mount Sidekiq::Web=> '/sidekiq'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :listings_photos
  has_many :bookings
  include PgSearch
  pg_search_scope :search, against: [:title, :description, :address, :country, :city, :state],
  using: {tsearch: {dictionary: "english"}}

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodates, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence:true

  def self.text_search(query)
    if query.present?
      search(query)
    else
      Listing.all
    end
  end

  def self.available_listings(query, search_check_in_date, search_check_out_date)

    listings = Listing.all

    available_listings = []

    listings.each do |listing|
      overlap = []
      if listing.bookings.present?
        listing.bookings.each do |booking|

            overlap << booking.overlap?(Date.parse(search_check_in_date), Date.parse(search_check_out_date), booking)
        end
        available_listings << listing unless overlap.include?(true)
      else
        available_listings << listing
      end
    end

    available_listings
  end
end

app/controllers/listings_controller.rb
class ListingsController <ApplicationController

  def index
    @listings = current_user.listings
  end

  def new
    @current_listing = Listing.new
  end

  def create
    # create new listing object
    @current_listing = Listing.new(listing_params)
    # if there're a current user
    if current_user
      # set current listing object's user id to current user id
      @current_listing.user_id = current_user.id
      # if currrent listing is valid and saved,
      if @current_listing.valid? && @current_listing.save
        #  redirect to home
        redirect_to @current_listing
      else
        # redirect to new listing path and flash msgs
        flash[:error] = "Listing requirement doesn't meet!"
        redirect_to new_listing_path
      end
      # end inner if
    else
      # redirect to log in page and flash msgs
      flash[:warning] = "Please sign in first to list your space!"
      redirect_to new_session_path
    end
    # end outer if
  end

  def show
    @new_booking = Booking.new
    @current_listing = Listing.find(params[:id])
    @blocked_dates = get_blocked_dates(@current_listing)
  end

  def edit
    @current_listing = Listing.find(params[:id])
  end

  def update

   if @current_listing.update_attributes(listing_params)
     render 'show'
   else
     render 'edit'
   end
  end

  def listing_params
    # strong params
    params.require(:listing).permit(:photos, :title, :description, :price, :home_type, :room_type, :accommodates, :address, :city, :postal_code, :state, :country)
  end



end

app/helpers/listings_helper.rb
module ListingsHelper

  def home_types
    ["Apartment", "House", "Bed & Breakfast", "Loft", "Townhouse", "Condominium", "Bungalow", "Cabin", "Villa", "Castle", "Dorm", "Treehouse", "Boat", "Plane", "Camper/RV", "Igloo", "Lighthouse", "Yurt", "Tipi", "Cave", "Island", "Chalet"]
  end

  def room_types
    ["Entire home/apt", "Private room", "Shared room"]
  end

  def countries_list
    countries = Country.all
    countries.map! do |country|
        country.name
    end
    countries.sort!
  end
end

app/views/listings/edit.html.erb
<header class="container navbar-buffer">
  <h2>Editing <%= @current_listing.title %></h2>
</header>

<div class="container">
  <%= link_to "Back to Listing", listing_path(@current_listing), class: "btn btn-info" %>
  <%= simple_form_for @current_listing, html: {class: "hero-form", multipart: true}, url: listing_path, method: :patch do |f| %>
    <%= f.input :title, required: true%>
    <%= f.input :description, required: true %>
    <%= f.input :price, required: true %>
    <%= f.input :home_type, default: home_types[0], collection: home_types %>
    <%= f.input :room_type, default: room_types[0], collection: room_types %>
    <%= f.input :accommodates, default: 1, collection: 1..16 %>
    <%= f.input :address, required:true %>
    <%= f.input :city, required:true %>
    <%= f.input :postal_code, label: "Postal code" %>
    <%= f.input :state, required: true %>
    <%= f.input :country, default: countries_list[0], collection: countries_list, label: "Country" %>
    <%= f.button :submit, value: "Update" %>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="container">
  <header class="navbar-buffer">
    <h2>Your listings: </h2>
  </header>
  
  <div class="user-listings-body">
    <% @listings.each do |listing| %>
    <%= link_to (listing) do %>
      <h3>Title: </h3>
      <h4><%= listing.title %></h4>
      <h3>Description:</h3>
      <h4><%= listing.description %></h4>
    <% end %>
      <hr>
    <% end %>
  </div>

</div>

app/views/listings/new.html.erb
<header>

</header>

<div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
  </div>
  <div class="listing-body col-sm-4 col-md-4 col-lg-4">
    <%= simple_form_for @current_listing, url: create_listing_path do |f|%>
      <%= f.input :title, required: true%>
      <%= f.input :description, required: true %>
      <%= f.input :price, required: true %>
      <%= f.input :home_type, default: home_types[0], collection: home_types %>
      <%= f.input :room_type, default: room_types[0], collection: room_types %>
      <%= f.input :accommodates, default: 1, collection: 1..16 %>
      <%= f.input :address, required:true %>
      <%= f.input :city, required:true %>
      <%= f.input :postal_code, label: "Postal code" %>
      <%= f.input :state, required: true %>
      <%= f.input :country, default: countries_list[0], collection: countries_list, label: "Country" %>
      <%= f.button :submit, value: "Submit" %>

    <% end %>

  </div>
  <div class="col-sm-4 col-md-4 col-lg-4">
  </div>
</div>

app/views/listings/show.html.erb
<div class="navbar-buffer">

</div>
<div class="container">
  <header>
  <h1><%= @current_listing.title %></h1>
  </header>

  <div class="listing-body">

    <% if user_logged_in? && (@current_listing.user_id).to_i == current_user.id %>
      <%= link_to "Edit Listing", edit_listing_path, class: "btn btn-info" %>

    <% else %>

    <div class="row">
      <div class="col-sm-6 col-md-6 col-lg-6">

        <%= form_for @new_booking, url: bookings_path, method: :post, id: "booking-container" do |f| %>
            <div class="input-group">

              <span class="input-group-addon">FROM</span>
              <%= f.text_field :check_in_date, label:false, placeholder: "Check In Date", class: "input-md form-control", id: "check-in-datepicker", readonly: true %>
              <span class="input-group-addon">TO</span>
              <%= f.text_field :check_out_date, label:false, placeholder: "Check Out Date", class: "input-md form-control", id: "check-out-datepicker", readonly: true%>
              <%= f.hidden_field :blocked_dates, value: @blocked_dates %>
              <% if current_user.present? %>
                <%= f.hidden_field :customer_id, value: current_user.id %>
              <% end %>
              <%= f.hidden_field :listing_id, value: @current_listing.id %>
              <span class="input-group-btn">
                <%= f.submit "Book it!", class: "btn btn-danger"%>
              </span>
            </div>
        <% end %>
      </div>
      <div class="col-sm-6 col-md-6 col-lg-6"></div>
    </div>

    <% end %>

    <h4>Gallery:</h4>

      <% if user_logged_in? && (@current_listing.user_id).to_i == current_user.id && @current_listing.listings_photos.empty?%>

        <%= simple_form_for :listing_info, url: new_listings_photo_path, method: :get do |f| %>
          <%= f.hidden_field :listing_id, as: :hidden,value: @current_listing.id  %>
          <%= f.button :submit, value: "Add Photos", class: "btn btn-info" %>
        <% end %>

      <% elsif user_logged_in? && (@current_listing.user_id).to_i == current_user.id %>

        <% @current_listing.listings_photos.each do |photo| %>
        <%= image_tag(photo.listing_photo_url(:display)) %>
        <% end %>

        <%= simple_form_for :listing_info, url: edit_listings_photo_path, method: :get do |f| %>
          <br/>
          <%= f.button :submit, value: "Edit Gallery", class: "btn btn-info" %>
        <% end %>

      <% end %>

    <br/>
    <h4>Description:</h4>
    <p>
      <%= @current_listing.description %>
    </p>
  </div>
</div>