config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, except: [:new, :create]
  get "/sign_up", to: "registrations#new", as: "sign_up_form"
  post "/sign_up", to: "registrations#create", as: "sign_up"

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create_fb_session'
  get 'auth/failure', to: redirect('/')

  resources :listings, except: [:create]
  post "/listings/create", to: "listings#create", as: "create_listing"

  resources :listings_search, only: [:index, :create]

  resources :listings_photos, except: [:delete, :index]

  resources :bookings

  require 'sidekiq/web'
  mount Sidekiq::Web=> '/sidekiq'
end

app/views/shared/partials/navbar/_logged_in_nav_elements.html.erb
<li><%= link_to "Your Listings", listings_path %></li>


<li class="dropdown">
  <a href="#" class="dropdown-toggle logged-in-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <span id="navbar-name"><%= current_user.first_name.capitalize %></span>

    <% if current_user.facebook_photo.nil? %>
      <%= image_tag(current_user.avatar_url(:thumbnail), alt: "user profile photo", width: 30, height: 30, class: "navbar_icon") %>
    <% else %>
      <%= image_tag(current_user.facebook_photo, alt: "user facebook photo", width: 30, height: 30, class: "navbar_icon") %>
    <% end %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "User Profile", user_path(current_user) %></li>
    <li><%= link_to "Log Out", session_path(current_user), method: :delete %></li>
  </ul>
</li>

app/views/shared/partials/navbar/_not_logged_in_nav_elements.html.erb
<li><%= link_to "Sign Up", sign_up_form_path %></li>
<li><%= link_to "Sign In", new_session_path %></li>