config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, except: [:new, :create]
  get "/sign_up", to: "registrations#new", as: "sign_up_form"
  post "/sign_up", to: "registrations#create", as: "sign_up"

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create_fb_session'
  get 'auth/failure', to: redirect('/')

  resources :listings, except: [:create]
  post "/listings/create", to: "listings#create", as: "create_listing"

  resources :listings_search, only: [:index, :create]

  resources :listings_photos, except: [:delete, :index]

  resources :bookings

  require 'sidekiq/web'
  mount Sidekiq::Web=> '/sidekiq'
end

app/models/listings_photo.rb
class ListingsPhoto < ActiveRecord::Base
  belongs_to :listing

  mount_uploader :listing_photo, ListingsPhotosUploader
  
end

app/controllers/listings_photos_controller.rb
class ListingsPhotosController <ApplicationController
  def new
    @current_listing = Listing.find(listing_params[:listing_id])
    @listings_photo = ListingsPhoto.new
  end

  def create

    if !listing_photo_params[:photos].nil?
      photos = listing_photo_params[:photos]
      photos.each do |photo|
        new_photo = ListingsPhoto.new
        new_photo.listing_photo = photo
        new_photo.listing_id = listing_photo_params[:listing_id]
        new_photo.save
      end
    end
    redirect_to listing_path(Listing.find(listing_photo_params[:listing_id]))
  end

  def edit
    @listings_photo = ListingsPhoto.new
  end

  def update
    if !listing_photo_params[:photos].nil?
      photos = listing_photo_params[:photos]
      photos.each do |photo|
        new_photo = ListingsPhoto.new
        new_photo.listing_photo = photo
        new_photo.listing_id = params[:id]
        new_photo.save
      end
    end
    if params[:remove_photos].present?
      params[:remove_photos].each do |photo_id|
        ListingsPhoto.find(photo_id).destroy!
      end
    end
    redirect_to listing_path(Listing.find(listing_photo_params[:listing_id]))
  end

  def listing_photo_params
    params.require(:listings_photo).permit(:listing_id, photos: [])
  end

  def listing_id_params
      params.permit(:id)
  end

  def listing_params
    params.require(:listing_info).permit(:listing_id)
  end
end

app/views/listings_photos/edit.html.erb
<div class="container">
  <header class="navbar-buffer">
    <h2>Edit Gallery:</h2>
  </header>

  <div class="upload-photos-body">
    <%= simple_form_for @listings_photo, html: {multipart: true}, url: listings_photo_path, method: :patch do |f| %>
      <%= f.hidden_field :listing_id, value: params[:id] %>
      <% current_listing = Listing.find(params[:id]) %>
      <% if (current_listing.listings_photos).present? %>
        <% current_listing.listings_photos.each do |listings_photo| %>
          <%= image_tag(listings_photo.listing_photo_url(:display)) %>
          <br>
          <%= check_box_tag 'remove_photos[]', listings_photo.id %>
          delete this photo
          <br><br>
        <% end %>
      <% end %>
      <label for="listings_photos">Listing's Photos</label>
      <%= f.file_field :photos, multiple: true  %>
      <br>
      <%= f.button :submit, value: "Update Gallery", class: "btn btn-info" %>
    <% end %>
  </div>
</div>

app/views/listings_photos/new.html.erb
<div class="container">
  <header class="navbar-buffer">
    <h2>Upload Photos:</h2>
  </header>

  <div class="upload-photos-body">
    <%= simple_form_for @listings_photo, html: {multipart: true}, url: listings_photos_path, method: :create do |f| %>
      <%= f.hidden_field :listing_id, value: @current_listing.id %>
      <label for="listings_photos">Listing's Photos</label>
      <%= f.file_field :photos, multiple: true  %>
      <br>
      <%= f.button :submit, value: "Add Photos", class: "btn btn-info" %>
    <% end %>
  </div>
</div>